### ISSUE TITLE
Update slot's copy/paste functionality and `onClick` interactivity: 2 pts

### ISSUE THREAD

**Issue by ikusteu** [eisbuk/EisBuk#245]
There is an issue when we want to delete or edit a selected slot (or slot available for selection, part of week in clipboard). We can't do it as the click event bubbles to the parent (slot card).

**Comment by silviot** [comment]
I agree with stopping event bubbling when clicking "delete" on a selected slot.

Regarding clearing the clipboard on paste, I'm a bit conflicted, for two reasons. The most important is that the typical use case for copy/paste is when you're preparing the slots for next month. Typically you'll copy a week from the past, paste it in the first week of the upcoming month and do some adjustments. Then you'll copy the new adjusted week and paste it three (or four) times in the following weeks. Clearing the clipboard after each paste will make this process more tedious.
The other reason is that I believe the correct solution for this kind of problem is having a working "undo" functionality, but I don't think we'll get to implement it for this project. In any case, if pasting-by-mistake becomes a common problem, we still have the option of implementing an undo just for the paste operations (since undoing them by hand can be time consuming).

**Comment by ikusteu** [comment]
Right, ok

**Comment by ikusteu** [comment]
I would actually suggest having an undo options, to which we can attach an additional reporting script so that we can keep track of the frequency of those mistakes for cost/benefit of eliminating possibility for said errors
