### ISSUE TITLE
Feature: Customer_Area Page re-writes: 8 pts

### ISSUE THREAD

**Issue by delasous** [eisbuk/EisBuk#502]
An initial discussion ticket to track actions/updates for `customer_area/*` files post- completion of component tickets. Feel free to edit directly or comment

- #501 is a WIP of updates to athlete/customer route navigation
- [ ] Assess work for `BookingsCalendar` and `CustomerSlots`
- [ ] Create a shared `__layout` component for pages that  uses #500 & #493, and passes main content as children? (Chris to expand on this)
- [ ] Remove unused components from `packages/client`

**Comment by ikusteu** [comment]
> Create a shared __layout component for pages that uses https://github.com/eisbuk/EisBuk/issues/500 & https://github.com/eisbuk/EisBuk/issues/493, and passes main content as children? (Chris to expand on this)

1. Let's not mix this with Svelte kit (I know and like the `__layout` naming, but that's a Svelte convention, in React, especially  React SPA, no SSR, we can just name the component `<Layout>`)

2. It makes sense to add the top bar to layout, but not the date nav as it might or might not be used across the app (`customers` view doesn't use it, for instance)

3. Furthermore, as much as I applaud the use of a shared `Layout` component (and we can most definitely make it a separate component), it can just be rendered in `App.tsx`, engulfing the `Router`, (and routes for each page). Using a shared layout component and doing
```jsx
<Layout>
  <PageComponent(s) {...} />
</Layout>
```
for each page makes sense in SSR (Next.js would be the closest in this, React, context) because there's no central `App.tsx` (page routing is done by page file names) and `__app.tsx` is, by convention, used to hold a central data store (Redux, context, etc.), while each page should have it's full (JSX) content in file (hence the engulfing `<Layout>` in each file)

**Comment by ikusteu** [comment]
**Add to previous comment:** 
- regarding point `3.`: Layout can also be used per page/view basis when we want to pass different props with respect to page/view.

- after #500 is developed, it can be used instead of `Layout` component (as it's the only thing shared between views at the moment). If we encounter the need for more items to be part of layout, a separate component can be made ofc

**Comment by silviot** [comment]
Closing as this ticket was used as a discussion base.
