### ISSUE TITLE
Feature: CustomerForm Page

### ISSUE THREAD

**Issue by delasous** [eisbuk/EisBuk#595]
Holding place for tasks that need to follow in the wake of feature tickets for form components and dropdown.

Implements #504

## Description
Page will use #592, and pass it the existing `updateCustomer` action to fire onSubmit + existing customer facts for form initial values. This work will also need to update UserAvatar in Layout to be an anchor for the "Settings" dropdown

## Tasks
1. Existing actions `updateCustomer` action used Admin side can probably be re-used here without any re-work
    1. `stores/actions/CustomerOperations`
2. Use appropriate selector to get current user (this is likely already being used in new CustomerArea page.

**Comment by ikusteu** [comment]
> Link to this page from Admin side when editing a cutomer to advance rewrites of Admin side?
Maybe not, because Admin side has additional fields, or at least:
“Extended Booking Date” is a special case, which opens yet another modal to confirm action. If this is required, need to redesign.

I definitely agree on using this as an edit from admin side. We can make this a `/athlete/<athlete_id>` route. There already exists an auth selector `getIsAdmin` which can be used to easily determine if the current user is logged in as admin. If so, additional fields would be shown, if not, only the self-editing fields should be shown. 
This should be reflected in Customer Form component (by accepting isAdmin and rendering/not rendering certain fields), bu it could be done as an second pass enhancement.
