### ISSUE TITLE
Extend bookings for an athlete is not working

### ISSUE THREAD

**Issue by silviot** [eisbuk/EisBuk#741]
The button for letting a single athlete manage their bookings after the deadline always returns an error. Or at least I was not able to make it work.

It never complains about an invalid date, so it's probably missing date validation.

**Comment by ikusteu** [comment]
The reason for this not working is that the existing (dummy) customers had invalid phone numbers and our firestore rules don't allow for updates to customers with invalid phone numbers (among other validation checks). I've created a migration function to remove all invalid phone numbers from customers (as no-phone is allowed by validation).

The fix for this is merged in #742 (and deployed). I ran it in eisbuk.web.app and it fixed the problem.

@silviot I'll leave it to you to do it in production (run `Remove invalid customer phones` from `/debug`) and close the issue when the fix is verified.
