### ISSUE TITLE
Athletes can't book. They get "Firestore permission denied"

### ISSUE THREAD

**Issue by silviot** [eisbuk/EisBuk#804]
To make this work in production I replaced the current `firestore.rules` file with these contents:

```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if true;
    }
  }
}
```
I did it from the console. I'll update code in the repo too.

**Comment by fadwamahmoud** [comment]
There are two culprits behind the bug:

    A few of the slots that can't be booked have data discrepancies (they have extra props which shouldn't be there className"w-full" and selected:false)
    The majority of this bug is that the slots from September and October are mixed up (they're both showing in both months)
    So when an athlete tries to book a slot while they're in September and that slot actually belongs in October it'll show that error.

**Comment by fadwamahmoud** [comment]
Root cause is slotsByDay having multiple dates with the same slots
![Untitled(1)](https://github.com/eisbuk/EisBuk/assets/41344489/1a0bfb78-ee0f-47e6-a0f2-c82fa186e4bd)
![Untitled](https://github.com/eisbuk/EisBuk/assets/41344489/7676a92e-ab7c-43c0-849a-bad3082dcfc5)

**Comment by fadwamahmoud** [comment]
I have a hunch that this was caused by the copy/paste bug somehow since the duplicate slots are exactly the same, but I can't go any further than that. I suggest we fix the data manually since it's just these specific dates that cause the error (new slots can be booked fine) by deleting one of each duplicate set of slots and creating the deleted slots again. @silviot @ikusteu

**Comment by silviot** [comment]
@fadwamahmoud So the attempted (and failed) copy/paste operations did result in changes of the database, if I understand correctly.

If that is the case I think we can manually remove the faulty records from production, but only as long as we save the existing bad records to track down the original problem.

A side note: a relational database would have prevented that. Typically a web server would rollback its current transaction and any change performed in the current request would be discarded.

**Comment by fadwamahmoud** [comment]
The copy/paste guess is just a hunch because I couldn't find another reasonable explanation after failing to find a bug; I could be totally wrong @silviot 
@ikusteu feel free to take a look maybe this needs a fresh set of eyes

**Comment by ikusteu** [comment]
Partially related to this: I've opened up [this discussion](https://github.com/eisbuk/EisBuk/discussions/809) related to datamodel and complex data flows.

**Comment by ikusteu** [comment]
I wouldn't say it was caused by copy/paste bug. I've fixed the copy/paste bug and have opened up a PR (#810), but then I realised this was about booking, not the copy/paste...anyhow, I wasn't able to reproduce this....could be that the different implementation of copy/paste (for client variant) worked with some earlier (minor) version of firebase/firestore SDK and has been updated to throw an error (when passing empty string or `undefined` as `doc()` path.

I will dig through a little more and try to find where else can slots get updated: My hunch is that there's an update somewhere that updates the slot's date, leaving the slot id the same...copy/paste **would** be the first suspect, but, as stated, I don't think it is

**Comment by ikusteu** [comment]
After a fair amount of debugging, I couldn't reproduce the mismatch that caused this error. The simple solution seems to be to manually delete the problematic slots and track the error (if it happens again) using sentry + firebase logging, as described in [this comment](https://github.com/eisbuk/EisBuk/issues/807#issuecomment-1712901383)

**Comment by silviot** [comment]
I'd like to take action to make sure this problem doesn't surface again. Or, if it surfaces again, it does with enough info for us to fully solve it.

My unserstanding is that we identified the condition that triggers the problem: having two slots in two different days share the same id.

I propose we
* remove the faulty slots from production
* add a rule that makes the db reject them
* if the above is not possible (for limitations of the rules environment) then write a trigger function that checks for uniqueness on each new record creation or record id modification
* use the info we get from tracebacks to fix the problem (if we managed to write a rule about it) OR we observe how often the trigger fixes records and try to correlate that with user actions to find the source of the problem

**Comment by silviot** [comment]
https://github.com/eisbuk/EisBuk/assets/396425/0056b123-8eaa-4e37-a287-977404f5bd5d


Athletes get the "legit" entry (on the bottom), and it can be booked. But the "rogue"/"fake" entry (that does not have a corresponding attendance record - on the top) does not work.


https://github.com/eisbuk/EisBuk/assets/396425/e1028b17-cce1-4f02-a469-4d2a8b69e1c6

After editing the top slot and adding a description (`...`) the behaviour is reversed.

**Comment by ikusteu** [comment]
My reasoning for this:

**The initial state:**
- first slot had an id (let's use `slot-1`), and existed in `slotsByDay` under 7th Oct
- second slot had the same id and existed in `slotsByDay` under 8th Oct
- `slot-1` in `slots` collection had the date of 8th Oct
- **booking the former didn't work due to date mismatch (I think firestore rules checks for that), the booking of the latter did work as that's the proper date for the given slot** 

**The update:**
- the first slot got saved (as a slot), it still had the id of `slot-1` and the data (displayed in the UI) which got saved to the db, in slots collection, under the id of `slot-1`
- the data trigger ran, on an updated slot (`slot-1`) and updated the data in `slotsByDay`, for the slot under 7th Oct
- the second slot still exists in `slotsByDay` (it hadn't been touched by the slots by day data trigger as the document change (`slot-1` document) was an update, rather than delete, so only the `.after` had been taken into account

**Final state:**
- first slots exists in `slotsByDay` under 7th Oct
- second slots exists in `slotsByDay` under 8th Oct
- `slot-1` in `slots` collection has the date of 7th Oct
- the situation is effectively reversed

**Comment by ikusteu** [comment]
But, we're back at the initial bug which is: Why TF were there two `slotsByDay` entries with the same slot id.

**Comment by ikusteu** [comment]
@silviot, @fadwamahmoud has this been treated symptomatically: the bug manually removed, without much info as to what caused it, but stable in production? If so, can the issue be closed?

**Comment by silviot** [comment]
@ikusteu Yeah, it makes sense to close it for now. We can reference this conversation if the problem happens again.
